<a href="https://colab.research.google.com/github/amann1273/AIML-2303A51273/blob/main/ADM_Week_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as numpy
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/university_student.csv')

In [ ]:
print(df.head())

   Student ID  Gender Date of Birth  Study Time Grade School Type  Absences  \
0           1    Male    1996-12-03          11     D      Public         2
1           2  Female    2001-09-15           5     D     Private         0
2           3    Male    2002-08-09           8     A     Private         2
3           4    Male    1999-04-29           8     A     Private         3
4           5    Male    1995-06-11           9     B     Private         1

   Math Score  Reading Score  Writing Score
0          72             91             69
1          66             58             62
2          75             99             77
3          57             76             97
4          78             51             78

In [ ]:
print(df)

    Student ID  Gender Date of Birth  Study Time Grade School Type  Absences  \
0            1    Male    1996-12-03          11     D      Public         2
1            2  Female    2001-09-15           5     D     Private         0
2            3    Male    2002-08-09           8     A     Private         2
3            4    Male    1999-04-29           8     A     Private         3
4            5    Male    1995-06-11           9     B     Private         1
..         ...     ...           ...         ...   ...         ...       ...
95          96  Female    2004-12-04           8     C      Public         1
96          97  Female    2003-01-18           7     B     Private         4
97          98  Female    1999-01-24          14     A     Private         2
98          99  Female    2005-04-20           7     B     Private         1
99         100    Male    2004-12-25           7     B     Private         2

    Math Score  Reading Score  Writing Score
0           72             91             69
1           66             58             62
2           75             99             77
3           57             76             97
4           78             51             78
..         ...            ...            ...
95          87             85             88
96          56             76             87
97          95             66             83
98          62             58             87
99          89             82             99

[100 rows x 10 columns]

In [ ]:
df.describe()

,Student ID,Study Time,Absences,Math Score,Reading Score,Writing Score
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,9.810000,2.500000,76.030000,74.370000,74.850000
std,29.011492,3.298898,1.672716,13.481341,14.457639,15.763002
min,1.000000,5.000000,0.000000,53.000000,50.000000,50.000000
25%,25.750000,7.000000,1.000000,64.500000,61.750000,61.750000
50%,50.500000,10.000000,3.000000,74.500000,75.500000,75.500000
75%,75.250000,13.000000,4.000000,86.250000,86.250000,87.000000
max,100.000000,15.000000,5.000000,100.000000,99.000000,100.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student ID     100 non-null    int64
 1   Gender         100 non-null    object
 2   Date of Birth  100 non-null    object
 3   Study Time     100 non-null    int64
 4   Grade          100 non-null    object
 5   School Type    100 non-null    object
 6   Absences       100 non-null    int64
 7   Math Score     100 non-null    int64
 8   Reading Score  100 non-null    int64
 9   Writing Score  100 non-null    int64
dtypes: int64(6), object(4)
memory usage: 7.9+ KB

In [ ]:
df.columns

Index(['Student ID', 'Gender', 'Date of Birth', 'Study Time', 'Grade',
       'School Type', 'Absences', 'Math Score', 'Reading Score',
       'Writing Score'],
      dtype='object')

In [ ]:
df.isnull().sum()

Student ID       0
Gender           0
Date of Birth    0
Study Time       0
Grade            0
School Type      0
Absences         0
Math Score       0
Reading Score    0
Writing Score    0
dtype: int64

In [ ]:
df_encoded=pd.get_dummies(df,columns=['Gender','School Type'],drop_first=True)

In [ ]:
df_encoded

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public
0,1,1996-12-03,11,D,2,72,91,69,True,True
1,2,2001-09-15,5,D,0,66,58,62,False,False
2,3,2002-08-09,8,A,2,75,99,77,True,False
3,4,1999-04-29,8,A,3,57,76,97,True,False
4,5,1995-06-11,9,B,1,78,51,78,True,False
...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,C,1,87,85,88,False,True
96,97,2003-01-18,7,B,4,56,76,87,False,False
97,98,1999-01-24,14,A,2,95,66,83,False,False
98,99,2005-04-20,7,B,1,62,58,87,False,False
99,100,2004-12-25,7,B,2,89,82,99,True,False

In [ ]:
df_encoded['Gender_Male']=df_encoded['Gender_Male'].astype(int)

In [ ]:
df_encoded

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public
0,1,1996-12-03,11,D,2,72,91,69,1,True
1,2,2001-09-15,5,D,0,66,58,62,0,False
2,3,2002-08-09,8,A,2,75,99,77,1,False
3,4,1999-04-29,8,A,3,57,76,97,1,False
4,5,1995-06-11,9,B,1,78,51,78,1,False
...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,C,1,87,85,88,0,True
96,97,2003-01-18,7,B,4,56,76,87,0,False
97,98,1999-01-24,14,A,2,95,66,83,0,False
98,99,2005-04-20,7,B,1,62,58,87,0,False
99,100,2004-12-25,7,B,2,89,82,99,1,False

In [ ]:
df_encoded['School Type_Public']=df_encoded['School Type_Public'].astype(int)

In [ ]:
df_encoded

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public
0,1,1996-12-03,11,D,2,72,91,69,1,1
1,2,2001-09-15,5,D,0,66,58,62,0,0
2,3,2002-08-09,8,A,2,75,99,77,1,0
3,4,1999-04-29,8,A,3,57,76,97,1,0
4,5,1995-06-11,9,B,1,78,51,78,1,0
...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,C,1,87,85,88,0,1
96,97,2003-01-18,7,B,4,56,76,87,0,0
97,98,1999-01-24,14,A,2,95,66,83,0,0
98,99,2005-04-20,7,B,1,62,58,87,0,0
99,100,2004-12-25,7,B,2,89,82,99,1,0

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoder = LabelEncoder()

In [ ]:
df_encoded['Grade']=label_encoder.fit_transform(df_encoded['Grade'])

In [ ]:
df_encoded

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public
0,1,1996-12-03,11,3,2,72,91,69,1,1
1,2,2001-09-15,5,3,0,66,58,62,0,0
2,3,2002-08-09,8,0,2,75,99,77,1,0
3,4,1999-04-29,8,0,3,57,76,97,1,0
4,5,1995-06-11,9,1,1,78,51,78,1,0
...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,2,1,87,85,88,0,1
96,97,2003-01-18,7,1,4,56,76,87,0,0
97,98,1999-01-24,14,0,2,95,66,83,0,0
98,99,2005-04-20,7,1,1,62,58,87,0,0
99,100,2004-12-25,7,1,2,89,82,99,1,0

In [ ]:
df_encoded['Date of Birth'] = pd.to_datetime(df_encoded['Date of Birth'], format='%d/%m/%Y', errors='coerce')

In [ ]:
df_encoded['Age']=pd.to_datetime('today').year - df_encoded['Date of Birth'].dt.year

In [ ]:
df_encoded['Total Score'] = df_encoded['Math Score'] + df_encoded['Reading Score'] + df_encoded['Writing Score']

In [ ]:
df_encoded

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public,Age,Total Score
0,1,NaT,11,3,2,72,91,69,1,1,NaN,232
1,2,NaT,5,3,0,66,58,62,0,0,NaN,186
2,3,NaT,8,0,2,75,99,77,1,0,NaN,251
3,4,NaT,8,0,3,57,76,97,1,0,NaN,230
4,5,NaT,9,1,1,78,51,78,1,0,NaN,207
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,NaT,8,2,1,87,85,88,0,1,NaN,260
96,97,NaT,7,1,4,56,76,87,0,0,NaN,219
97,98,NaT,14,0,2,95,66,83,0,0,NaN,244
98,99,NaT,7,1,1,62,58,87,0,0,NaN,207
99,100,NaT,7,1,2,89,82,99,1,0,NaN,270